name: graphka
version: scm-1
deps:
  - https://raw.githubusercontent.com/moonlibs/config/master/config-scm-1.rockspec
  - https://raw.githubusercontent.com/moonlibs/package-reload/master/package.reload-scm-1.rockspec
  - https://raw.githubusercontent.com/igorcoding/tarantool-spacer/master/rockspecs/spacer-scm-2.rockspec
  - https://raw.githubusercontent.com/bjornbytes/RxLua/master/rockspec/rxlua-0.0.3-1.rockspec
tntdeps: {}
